### ISSUE TITLE
polyfill.php required for Windows

### ISSUE THREAD

**Issue by dacgray** [crazyfactory/skeletor#2]
Fatal error: Call to undefined function ...readline()  on Create.php line 147 in Windows.

Can fix with 

require_once 'polyfill.php';

**Comment by cyberhck** [comment]
That is a little dirty solution, after I'm done with some of task I've to do, I'll look into this.

Yes it can be fixed with that but it breaks PSR2 standards, so I decided not to have it, but use a autoloader. Or I can do inside the class itself :) Should be fixed soon :)

**Comment by cyberhck** [comment]
on it :)
